pipeline {
  agent none
  stages {
    stage('Back-end') {
      agent {
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps {
        git branch: 'master', 
        credentialsId: '2a4edef0-7e36-4031-903a-84cd9af04b79', 
        poll: false, 
         url: 'https://github.com/regantithejesh/simple-java-project'
        sh 'mvn --version'
        sh 'mvn install'  
      }
    }
    stage('Front-end') {
      agent {
        docker { image 'node:16-alpine' }
      }
      steps {
        git branch: 'master', 
        credentialsId: '2a4edef0-7e36-4031-903a-84cd9af04b79', 
        poll: false, 
        url: 'https://github.com/regantithejesh/node-hello'
        sh 'node --version'
        sh 'npm start'
      }
    }
  }
}
